print("fråga inte varför jag gjorde dethär")

print("hur många vill äta 2 korvar")
tvåkorv=int(input("> "))
print("hur många vill äta 3 korvar")
trekorv=int(input("> "))
print("hur många vill äta 2 veganska korvar")
tvåvkorv=int(input("> "))
print("hur många vill äta 3 veganska korvar")
trevkorv=int(input("> "))
antalpackkorv=tvåkorv*2+trekorv*3
apk=int(antalpackkorv/8)
# print("du behöver köpa", str(apk), "förpackningar korvar")
antalpackVkorv=tvåvkorv*2+trevkorv*3
apVk=int(antalpackVkorv/4)
# print("du behöver köpa", str(apVk), "förpackningar vego korvar")
dryck=tvåkorv+trekorv+tvåvkorv+trevkorv
# print("du behöver köpa in", str(dryck), ("drickor"))
betala=int(apk*20.95+apVk*34.95+dryck*13.95)
# print("kostnaden blir", str(betala), "kr")
print(".:KORVKOLLEN:.")
print("----------------------------")
print("Hur många elever vill ha...")
print("2 vanliga korvar -",str(tvåkorv))
print("3 vanliga korvar -",str(trekorv))
print("2 veganska korvar -",str(tvåvkorv))
print("4 veganska korvar -",str(trevkorv))
print("----------------------------")
print("-INKÖPSLISTA-")
print("----------------------------")
print("Vanlig korv:",str(apk),"förpackningar")
print("Vegansk korv:",str(apVk),"förpackningar")
print("Dryck:",str(dryck),"drickor")
print("----------------------------")
print(str(betala), "SEK")
print("----------------------------")